#Question link
#https://leetcode.com/problems/find-the-difference/

#You are given two strings s and t.

#String t is generated by random shuffling string s and
#then add one more letter at a random position.

#Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in t :
            if i not in s :
                return i
            elif t.count(i) > s.count(i):

                return i
